"""
Heuristic summarization engine for video_context_analyzer.

Used as the fallback when no OPENAI_API_KEY is configured.
All logic is intentionally simple and readable — appropriate for a hackathon prototype.
"""

from __future__ import annotations

import re
from collections import Counter
from datetime import datetime, timezone
from statistics import mean
from typing import Any, Dict, List, Optional
from urllib.parse import urlparse

from app.models import CommentRecord


# ── Stop-words (common English words to ignore in keyword extraction) ─────────

_STOP_WORDS = {
    "a", "an", "the", "and", "or", "but", "in", "on", "at", "to", "for",
    "of", "with", "is", "it", "this", "that", "was", "are", "be", "as",
    "by", "from", "have", "has", "had", "not", "so", "if", "its", "i",
    "my", "me", "we", "you", "he", "she", "they", "do", "did", "just",
    "can", "will", "all", "more", "very", "get", "got", "one", "out",
    "up", "about", "what", "how", "when", "who", "which", "your", "his",
    "her", "their", "our", "been", "would", "could", "should", "no", "yes",
    "like", "im", "dont", "cant", "wont", "thats", "were", "than", "there",
    "then", "also", "even", "too", "some", "any", "now", "still", "well",
    "here", "into", "only", "after", "before", "over", "while", "those",
    "these", "other", "same", "most", "much", "many", "such",
}

# ── Source-type keyword classifier ────────────────────────────────────────────

_SOURCE_TYPE_SIGNALS: List[tuple[str, List[str]]] = [
    ("official/government", [
        "official", "government", "gov", "ministry", "parliament", "senate",
        "white house", "department", "federal", "president", "prime minister",
        "un ", "united nations", "who ", "fda", "cdc", "nasa",
    ]),
    ("news", [
        "news", "breaking", "report", "journalist", "media", "press",
        "bbc", "cnn", "nbc", "abc", "fox", "reuters", "ap ", "associated press",
        "times", "post", "herald", "gazette", "daily",
    ]),
    ("education", [
        "university", "college", "lecture", "tutorial", "lesson", "course",
        "explained", "learn", "khan", "ted ", "documentary", "science",
        "history", "professor", "academic",
    ]),
    ("brand/company", [
        "official channel", "brand", "product", "launch", "company",
        "corp", "inc", "ltd", "llc", "commercial", "advertisement", "ad",
        "sponsor",
    ]),
    ("entertainment", [
        "comedy", "funny", "prank", "vlog", "reaction", "music video",
        "trailer", "movie", "film", "series", "episode", "watch",
        "entertainment", "fun",
    ]),
    ("creator/influencer", [
        "podcast", "stream", "twitch", "patreon", "merch", "subscribe",
        "followers", "channel", "creator", "influencer",
    ]),
]

# ── Risk-flag keyword map ──────────────────────────────────────────────────────

_RISK_KEYWORD_MAP: List[tuple[str, List[str]]] = [
    ("politics", ["politic", "democrat", "republican", "election", "vote", "party", "congress", "senator", "legislat"]),
    ("elections", ["election", "ballot", "voter", "fraud", "rigged", "campaign", "candidate"]),
    ("war/conflict", ["war", "attack", "military", "troops", "bomb", "missile", "conflict", "invasion", "soldier", "ceasefire"]),
    ("public health", ["pandemic", "virus", "vaccine", "covid", "health", "disease", "outbreak", "infection", "mask"]),
    ("finance/investing", ["stock", "market", "invest", "crypto", "bitcoin", "economy", "inflation", "bank", "fund", "trade"]),
    ("conspiracy", ["conspiracy", "cover up", "cover-up", "hidden", "secret", "shadow", "globalist", "cabal", "new world order", "deep state"]),
    ("medical claims", ["cure", "treat", "miracle", "remedy", "heal", "drug", "dose", "clinical", "fda", "supplement"]),
    ("breaking news", ["breaking", "just in", "urgent", "alert", "developing", "exclusive"]),
    ("AI-generated", ["ai generated", "ai-generated", "artificial intelligence", "deepfake", "synthetic", "generated by ai", "made with ai"]),
    ("deepfake", ["deepfake", "fake video", "manipulated", "altered video", "synthetic media"]),
]

# ── Sentiment word lists (lightweight) ────────────────────────────────────────

_POSITIVE_WORDS = {
    "great", "awesome", "excellent", "love", "amazing", "good", "best",
    "brilliant", "wonderful", "fantastic", "thanks", "thank", "helpful",
    "informative", "correct", "truth", "right", "agree", "support", "nice",
}

_NEGATIVE_WORDS = {
    "bad", "wrong", "false", "fake", "lie", "liar", "misleading", "disagree",
    "terrible", "awful", "stupid", "biased", "propaganda", "misinformation",
    "nonsense", "ridiculous", "hate", "dangerous", "corrupt", "fraud",
}

_SKEPTICAL_WORDS = {
    "fake", "false", "wrong", "misleading", "lie", "liar", "doubt", "suspect",
    "fabricated", "staged", "propaganda", "hoax", "bs", "debunked",
}

_CORRECTIVE_PHRASES = {
    "actually", "correction", "fact check", "fact-check", "source", "citation",
    "evidence", "context", "not true", "that's wrong", "you are wrong",
}

_HOSTILE_WORDS = {
    "idiot", "stupid", "moron", "trash", "garbage", "scam", "fraud", "clown",
}

_SOURCE_REQUEST_WORDS = {
    "source", "sources", "citation", "evidence", "proof", "link", "links",
}

_INTENT_SIGNALS: List[tuple[str, List[str]]] = [
    ("reporting", ["breaking", "report", "news", "exclusive", "update", "press conference", "statement"]),
    ("commentary", ["opinion", "my take", "analysis", "reacts", "thoughts", "debate", "editorial"]),
    ("reaction", ["reaction", "reacting", "watching", "first time", "responding to"]),
    ("satire/comedy", ["satire", "parody", "comedy", "joke", "funny", "skit", "spoof"]),
    ("tutorial", ["how to", "tutorial", "guide", "step by step", "explained", "walkthrough"]),
    ("promotion", ["buy", "sale", "discount", "sponsored", "ad", "shop", "launch"]),
    ("testimonial", ["my story", "i tried", "my experience", "what happened to me", "testimony"]),
    ("clip", ["clip", "highlights", "best moments", "excerpt", "shorts"]),
    ("call_to_action", ["sign", "donate", "join", "share this", "take action", "support"]),
]


# ── Description summarizer ────────────────────────────────────────────────────


def summarize_description(description: str) -> str:
    """
    Extract the first 1–2 meaningful sentences from the video description.
    Returns a placeholder string if the description is empty.
    """
    if not description or not description.strip():
        return "No description provided."

    # Strip URLs and excessive whitespace
    cleaned = re.sub(r"https?://\S+", "", description)
    cleaned = re.sub(r"[ \t]+", " ", cleaned).strip()

    # Split into sentences (rudimentary but sufficient)
    sentences = re.split(r"(?<=[.!?])\s+", cleaned)
    meaningful = [s.strip() for s in sentences if len(s.strip()) > 30]

    if not meaningful:
        # Fall back to first 200 characters
        return cleaned[:200].strip() + ("…" if len(cleaned) > 200 else "")

    # Return up to 2 sentences, capped at 300 characters
    summary = " ".join(meaningful[:2])
    if len(summary) > 300:
        summary = summary[:300].rstrip() + "…"
    return summary


def summarize_channel_context(channel: Dict[str, Any], source_type: str) -> str:
    """Summarize the uploader using channel-level metadata."""
    if not channel:
        return "Channel-level context could not be retrieved."

    parts: list[str] = [f"This channel appears to be a {source_type} source."]
    if channel.get("subscriberCountHidden"):
        parts.append("Subscriber count is hidden.")
    elif channel.get("subscriberCount") is not None:
        parts.append(f"It has about {_format_views(channel['subscriberCount'])} subscribers.")
    if channel.get("videoCount") is not None:
        parts.append(f"The channel has published {channel['videoCount']:,} videos.")
    if channel.get("country"):
        parts.append(f"It is associated with {channel['country']}.")
    if channel.get("customUrl"):
        parts.append(f"Custom URL present: @{channel['customUrl']}.")
    return " ".join(parts)


def analyze_description_links(description: str) -> Dict[str, Any]:
    """Extract and summarize external links/domains from the description."""
    urls = re.findall(r"https?://[^\s)>\]]+", description)
    domains: list[str] = []
    for url in urls:
        netloc = urlparse(url).netloc.lower()
        if netloc.startswith("www."):
            netloc = netloc[4:]
        if netloc:
            domains.append(netloc)

    counts = Counter(domains)
    unique_domains = [domain for domain, _ in counts.most_common()]
    categories = []
    for domain in unique_domains:
        if any(token in domain for token in ("twitter.com", "x.com", "instagram.com", "facebook.com", "tiktok.com", "reddit.com")):
            categories.append("social")
        elif any(token in domain for token in ("substack.com", "medium.com", "wordpress.com", "blog")):
            categories.append("blog")
        elif any(token in domain for token in ("amazon.", "shop", "store", "gumroad.com", "patreon.com")):
            categories.append("commerce")
        elif any(token in domain for token in ("gov", "edu", "org", "who.int", "nih.gov")):
            categories.append("institutional")
        else:
            categories.append("general")

    if not unique_domains:
        summary = "No external links were found in the video description."
    else:
        summary = (
            f"The description links to {len(unique_domains)} distinct domains: "
            f"{', '.join(unique_domains[:5])}."
        )
        if "institutional" in categories:
            summary += " At least one linked domain looks institutional or source-like."
        elif "commerce" in categories and len(set(categories)) == 1:
            summary += " The outbound links appear primarily commercial."
        elif "social" in categories and len(set(categories)) == 1:
            summary += " The outbound links appear primarily social-platform links."

    return {
        "urls": urls,
        "domains": unique_domains,
        "domainCounts": dict(counts),
        "domainCategories": categories,
        "summary": summary,
    }


# ── Context / source-type classifier ─────────────────────────────────────────


def infer_source_type(channel_name: str, title: str, description: str) -> str:
    """
    Classify the likely source type of the video from channel name, title,
    and description text.

    Returns one of: news, official/government, creator/influencer, brand/company,
    education, entertainment, or general/unknown.
    """
    combined = f"{channel_name} {title} {description}".lower()

    scores: Counter = Counter()
    for source_type, keywords in _SOURCE_TYPE_SIGNALS:
        for kw in keywords:
            if kw in combined:
                scores[source_type] += 1

    if scores:
        return scores.most_common(1)[0][0]
    return "general/unknown"


def infer_content_intent(channel_name: str, title: str, description: str) -> str:
    """Infer the uploader's likely framing intent from text metadata."""
    combined = f"{channel_name} {title} {description}".lower()
    scores: Counter = Counter()
    for intent, keywords in _INTENT_SIGNALS:
        for kw in keywords:
            if kw in combined:
                scores[intent] += 1
    if "?" in title:
        scores["commentary"] += 1
    if title.isupper() and len(title) > 12:
        scores["reporting"] += 1
    if scores:
        return scores.most_common(1)[0][0]
    return "general"


def build_video_context_summary(
    channel_name: str,
    title: str,
    description: str,
    source_type: str,
    content_intent: str,
    views: Optional[int],
    channel_fit: str,
    engagement_profile: Dict[str, Any],
) -> str:
    """
    Compose a short human-readable context sentence for the video.
    """
    view_str = _format_views(views) if views is not None else "an unknown number of"
    return (
        f"This appears to be a {content_intent} video from a {source_type} source posted by "
        f"'{channel_name}'. The title is '{title[:80]}{'…' if len(title) > 80 else ''}', "
        f"and it has accumulated {view_str} views. Relative to recent channel uploads, "
        f"it looks {channel_fit}; engagement appears {engagement_profile.get('performanceBand', 'unclear')}."
    )


def _format_views(views: int) -> str:
    if views >= 1_000_000:
        return f"{views / 1_000_000:.1f}M"
    if views >= 1_000:
        return f"{views / 1_000:.1f}K"
    return str(views)


# ── Comment summarizer ────────────────────────────────────────────────────────


def summarize_comments(comments: list[CommentRecord], comments_enabled: bool) -> str:
    """
    Build a lightweight text summary of the comment section.
    """
    if not comments_enabled:
        return "Comments are disabled or unavailable for this video."

    if not comments:
        return "No comments were retrieved for this video."

    total = len(comments)
    pos, neg, neu = _sentiment_breakdown(comments)
    dynamics = analyze_comment_dynamics(comments, comments_enabled)
    top_words = _top_keywords(comments, top_n=8)
    keyword_str = ", ".join(top_words) if top_words else "varied topics"
    tone = _describe_tone(pos, neg, neu, total)
    polarized = dynamics.get("polarized", 0) > 0

    summary = (
        f"Analyzed {total} comments. "
        f"The overall tone is {tone}. "
        f"Frequently mentioned topics include: {keyword_str}."
    )
    if polarized:
        summary += " The discussion appears polarized, with both supportive and skeptical reactions."
    elif dynamics.get("corrective", 0) > 0:
        summary += " A visible subset of comments attempts to add correction or missing context."
    return summary


def analyze_playlist_context(playlist_context: Dict[str, Any]) -> str:
    """Summarize playlist/series context if the video is part of a playlist."""
    matches = playlist_context.get("playlistMatches", [])
    if not matches:
        return "No visible playlist membership was detected from the channel's scanned playlists."

    first = matches[0]
    sample_titles = first.get("sampleTitles", [])
    summary = (
        f"The video appears in the playlist '{first.get('title', '')}', which contains "
        f"{first.get('itemCount', 0)} items."
    )
    if sample_titles:
        summary += f" Nearby items include: {', '.join(sample_titles[:3])}."
    return summary


def cluster_channel_topics(history_videos: list[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Build coarse topic clusters from a larger channel-history sample."""
    term_counts: Counter = Counter()
    term_to_titles: Dict[str, list[str]] = {}
    for video in history_videos:
        terms = _tokenize_keywords(f"{video.get('title', '')} {video.get('description', '')}")
        seen: set[str] = set()
        for term in terms:
            if term in seen:
                continue
            seen.add(term)
            term_counts[term] += 1
            term_to_titles.setdefault(term, []).append(video.get("title", ""))

    clusters: list[Dict[str, Any]] = []
    for term, count in term_counts.most_common(6):
        if count < 3:
            continue
        clusters.append(
            {
                "label": term,
                "videoCount": count,
                "sampleTitles": term_to_titles.get(term, [])[:3],
            }
        )
    return clusters


def summarize_channel_history(history_videos: list[Dict[str, Any]], topic_clusters: list[Dict[str, Any]]) -> str:
    """Summarize the broader channel history and dominant recurring topics."""
    if not history_videos:
        return "No larger channel-history sample was available."
    if not topic_clusters:
        return f"Analyzed {len(history_videos)} recent uploads, but no strong recurring topic cluster stood out."

    top = topic_clusters[0]
    labels = ", ".join(cluster["label"] for cluster in topic_clusters[:4])
    return (
        f"Across {len(history_videos)} channel uploads, recurring topics include {labels}. "
        f"The strongest cluster is '{top['label']}', appearing in about {top['videoCount']} sampled uploads."
    )


def _sentiment_breakdown(comments: list[CommentRecord]) -> tuple[int, int, int]:
    pos = neg = neu = 0
    for c in comments:
        words = set(re.findall(r"\b\w+\b", c.text.lower()))
        p = len(words & _POSITIVE_WORDS)
        n = len(words & _NEGATIVE_WORDS)
        if p > n:
            pos += 1
        elif n > p:
            neg += 1
        else:
            neu += 1
    return pos, neg, neu


def _describe_tone(pos: int, neg: int, neu: int, total: int) -> str:
    if total == 0:
        return "unknown"
    pos_pct = pos / total
    neg_pct = neg / total
    if pos_pct > 0.5:
        return "mostly positive"
    if neg_pct > 0.5:
        return "mostly negative"
    if pos_pct > 0.3 and neg_pct > 0.3:
        return "mixed (both supportive and critical)"
    if neg_pct > 0.3:
        return "somewhat negative with criticism"
    if pos_pct > 0.3:
        return "generally positive"
    return "neutral or mixed"


def _top_keywords(comments: list[CommentRecord], top_n: int = 8) -> list[str]:
    word_counter: Counter = Counter()
    for c in comments:
        words = re.findall(r"\b[a-z]{4,}\b", c.text.lower())
        for w in words:
            if w not in _STOP_WORDS:
                word_counter[w] += 1
    return [w for w, _ in word_counter.most_common(top_n)]


# ── Top-themes extractor ──────────────────────────────────────────────────────


def extract_top_themes(
    comments: list[CommentRecord],
    title: str,
    description: str,
    top_n: int = 5,
) -> list[str]:
    """
    Identify the most prominent keyword themes from comments, title, and description.
    Returns a list of the top theme strings.
    """
    combined_text = f"{title} {description}"
    for c in comments:
        combined_text += f" {c.text}"
    combined_text = combined_text.lower()

    words = re.findall(r"\b[a-z]{4,}\b", combined_text)
    counts: Counter = Counter(w for w in words if w not in _STOP_WORDS)
    return [w for w, _ in counts.most_common(top_n)]


# ── Risk-flag inferrer ────────────────────────────────────────────────────────


def infer_risk_flags(
    title: str,
    description: str,
    channel_name: str,
    comments: list[CommentRecord],
) -> list[str]:
    """
    Identify risk-relevant topics based on keyword matching across all text fields.
    Returns a list of risk flag labels (may be empty).
    """
    combined = f"{title} {description} {channel_name}".lower()
    for c in comments:
        combined += f" {c.text.lower()}"

    flags: list[str] = []
    for flag_label, keywords in _RISK_KEYWORD_MAP:
        for kw in keywords:
            if kw in combined:
                flags.append(flag_label)
                break  # one match per category is enough

    return flags


def analyze_comment_dynamics(
    comments: list[CommentRecord],
    comments_enabled: bool,
) -> Dict[str, int]:
    """Classify comment-section dynamics into coarse behavioral buckets."""
    if not comments_enabled or not comments:
        return {
            "supportive": 0,
            "skeptical": 0,
            "corrective": 0,
            "hostile": 0,
            "source_requesting": 0,
            "polarized": 0,
        }

    supportive = skeptical = corrective = hostile = source_requesting = 0
    for comment in comments:
        text = comment.text.lower()
        words = set(re.findall(r"\b\w+\b", text))

        if words & _POSITIVE_WORDS:
            supportive += 1
        if words & _SKEPTICAL_WORDS or "?" in text and ("real" in text or "true" in text):
            skeptical += 1
        if any(phrase in text for phrase in _CORRECTIVE_PHRASES):
            corrective += 1
        if words & _HOSTILE_WORDS:
            hostile += 1
        if words & _SOURCE_REQUEST_WORDS or "where is the source" in text:
            source_requesting += 1

    polarized = int(supportive > 0 and skeptical > 0)
    return {
        "supportive": supportive,
        "skeptical": skeptical,
        "corrective": corrective,
        "hostile": hostile,
        "source_requesting": source_requesting,
        "polarized": polarized,
    }


def infer_claim_risk_score(
    title: str,
    description: str,
    content_intent: str,
    risk_flags: list[str],
    narrative_signals: list[str],
) -> int:
    """Estimate how likely the text metadata is making sensitive factual claims."""
    combined = f"{title} {description}".lower()
    score = 5

    claim_terms = ["is proof", "reveals", "exposes", "causes", "will happen", "cure", "fraud", "rigged", "truth about"]
    for term in claim_terms:
        if term in combined:
            score += 10

    if content_intent in {"reporting", "commentary", "testimonial"}:
        score += 10

    score += min(len(risk_flags) * 8, 24)
    if "urgent_framing" in narrative_signals:
        score += 8
    if "emotionally_loaded" in narrative_signals:
        score += 6
    if "source_missing" in narrative_signals:
        score += 10

    return max(0, min(score, 100))


def infer_narrative_signals(
    title: str,
    description: str,
    comments: list[CommentRecord],
) -> list[str]:
    """Infer higher-level narrative signals from metadata and comments."""
    text = f"{title} {description}".lower()
    signals: list[str] = []

    if any(term in text for term in ("breaking", "just in", "urgent", "alert", "happening now")):
        signals.append("urgent_framing")
    if "!" in title or title.isupper() or any(term in text for term in ("shocking", "must watch", "unbelievable")):
        signals.append("emotionally_loaded")
    if any(term in text for term in ("share", "join", "donate", "sign", "support", "subscribe now")):
        signals.append("call_to_action")
    if any(term in text for term in ("conspiracy", "cover up", "deep state", "they don't want you to know")):
        signals.append("conspiracy_language")
    if not re.search(r"https?://", description) and any(term in text for term in ("report", "study", "evidence", "source", "data")):
        signals.append("source_missing")

    joined_comments = " ".join(c.text.lower() for c in comments[:20])
    if any(term in joined_comments for term in ("fake", "misleading", "out of context", "where is the source")):
        signals.append("viewer_pushback")

    return signals


def analyze_freshness_and_repost_signals(
    title: str,
    description: str,
    published_at: str,
    comments: list[CommentRecord],
) -> Dict[str, Any]:
    """Detect freshness mismatch and repost/misleading-title cues."""
    text = f"{title} {description}".lower()
    comment_text = " ".join(c.text.lower() for c in comments[:30])
    signals: list[str] = []

    urgent_terms = ("today", "right now", "just happened", "breaking", "live", "happening now")
    if any(term in text for term in urgent_terms):
        published_dt = _parse_iso8601(published_at)
        if published_dt is not None:
            age_days = (datetime.now(timezone.utc) - published_dt).days
            if age_days > 30:
                signals.append("freshness_mismatch")
            if age_days > 365:
                signals.append("stale_but_currently_framed")

    if any(term in comment_text for term in ("reupload", "re-upload", "repost", "old video", "seen this before")):
        signals.append("possible_repost")
    if any(term in comment_text for term in ("misleading title", "clickbait", "out of context", "title is wrong")):
        signals.append("possible_misleading_title")
    if any(term in comment_text for term in ("this is old", "from last year", "not recent", "not new")):
        signals.append("viewer_dates_it_as_old")

    if not signals:
        summary = "No strong freshness mismatch or repost signals were detected from the metadata and comments."
    else:
        summary = (
            "Freshness/repost checks surfaced: " + ", ".join(signals) + ". "
            "These are cues from title/description framing and viewer feedback, not proof."
        )

    return {
        "signals": signals,
        "summary": summary,
    }


def analyze_channel_fit(video: Dict[str, Any], recent_videos: list[Dict[str, Any]]) -> str:
    """Estimate whether this upload is typical for the channel."""
    if not recent_videos:
        return "baseline unavailable"

    current_title_terms = set(_tokenize_keywords(video.get("title", "")))
    recent_title_terms = Counter()
    recent_lengths = []
    for recent in recent_videos:
        recent_lengths.append(len(recent.get("title", "")))
        recent_title_terms.update(_tokenize_keywords(recent.get("title", "")))

    overlap = sum(1 for term in current_title_terms if recent_title_terms.get(term, 0) > 0)
    avg_length = mean(recent_lengths) if recent_lengths else 0
    length_gap = abs(len(video.get("title", "")) - avg_length)

    if overlap <= 1 and length_gap > 20:
        return "atypical for this channel"
    if overlap <= 2:
        return "somewhat atypical"
    return "typical of the channel's recent uploads"


def build_engagement_profile(
    video: Dict[str, Any],
    recent_videos: list[Dict[str, Any]],
) -> Dict[str, Any]:
    """Compare the video's engagement with the recent channel baseline."""
    views = int(video.get("views") or 0)
    likes = int(video.get("likeCount") or 0)
    comments = int(video.get("commentCount") or 0)

    likes_per_thousand = round((likes / views) * 1000, 2) if views else 0.0
    comments_per_thousand = round((comments / views) * 1000, 2) if views else 0.0

    if not recent_videos:
        return {
            "baselineSampleSize": 0,
            "performanceBand": "unclear",
            "likesPerThousandViews": likes_per_thousand,
            "commentsPerThousandViews": comments_per_thousand,
            "summary": "No recent-upload baseline was available.",
        }

    avg_views = mean(max(v.get("views", 0), 1) for v in recent_videos)
    avg_likes = mean(v.get("likeCount", 0) for v in recent_videos)
    avg_comments = mean(v.get("commentCount", 0) for v in recent_videos)

    view_ratio = round(views / avg_views, 2) if avg_views else 0.0
    like_ratio = round((likes / avg_likes), 2) if avg_likes else 0.0
    comment_ratio = round((comments / avg_comments), 2) if avg_comments else 0.0

    if view_ratio >= 2.0:
        band = "well above channel baseline"
    elif view_ratio <= 0.5:
        band = "below channel baseline"
    else:
        band = "within normal channel range"

    return {
        "baselineSampleSize": len(recent_videos),
        "averageRecentViews": int(avg_views),
        "averageRecentLikes": int(avg_likes),
        "averageRecentComments": int(avg_comments),
        "viewRatioVsRecentAverage": view_ratio,
        "likeRatioVsRecentAverage": like_ratio,
        "commentRatioVsRecentAverage": comment_ratio,
        "likesPerThousandViews": likes_per_thousand,
        "commentsPerThousandViews": comments_per_thousand,
        "performanceBand": band,
        "summary": (
            f"The video is performing {band}, with {view_ratio}x the recent average views "
            f"and {comments_per_thousand} comments per thousand views."
        ),
    }


def summarize_context_risk(
    claim_risk_score: int,
    risk_flags: list[str],
    narrative_signals: list[str],
    comment_dynamics: Dict[str, int],
    channel_fit: str,
    freshness_signals: list[str],
) -> tuple[int, str]:
    """Combine multiple signals into a single context-risk score and explanation."""
    score = claim_risk_score
    score += min(len(risk_flags) * 5, 20)
    score += min(len(narrative_signals) * 4, 16)
    score += min(comment_dynamics.get("skeptical", 0), 10)
    score += min(comment_dynamics.get("corrective", 0), 10)
    score += min(comment_dynamics.get("source_requesting", 0) * 2, 10)
    if "atypical" in channel_fit:
        score += 8
    score += min(len(freshness_signals) * 6, 18)

    score = max(0, min(score, 100))

    if score >= 75:
        level = "high"
    elif score >= 45:
        level = "moderate"
    else:
        level = "low"

    summary = (
        f"Overall context risk appears {level}. This score is driven by the text framing, "
        f"topic sensitivity, visible viewer pushback, freshness/repost cues, and how unusual "
        f"the upload looks relative to the channel's recent output."
    )
    return score, summary


def _tokenize_keywords(text: str) -> list[str]:
    return [w for w in re.findall(r"\b[a-z]{4,}\b", text.lower()) if w not in _STOP_WORDS]


def _parse_iso8601(value: str) -> Optional[datetime]:
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None
